### ISSUE TITLE
Custom Title and Subtitle

### ISSUE THREAD

**Issue by grifas** [tiny2n/JKLLockScreenViewController#6]
Hi Everyone,

Is there a way to custom the titleLabel and subtitleLabel from a subclass of JKLLockScreenViewController with Delegate and DataSource ? I don't find it :/

Thank you,

**Comment by maulikpat** [comment]
Did you check : JKLLockScreenViewController.xib ?

**Comment by grifas** [comment]
Yes I checked it and I saw there are 2 linked labels (titleLabel, subtitleLabel) but how to set text programmatically ? I need differents texts for New, Normal, Change and Verification mode.

**Comment by savasadar** [comment]
I also need this feature but there is no such feature. You can change title and subtitle  from "JKLLockScreenViewController.m" file. But if you are using pod, you need change again every update/install pods :(
